var  Random = [
    "A surrealistic masterpiece of vibrant colors",
    "An abstract expression of emotions and dreams",
    "A whimsical creation inspired by nature",
    "A surreal composition blending reality and fantasy",
    "A thought-provoking artwork with hidden meanings",
    "An ethereal painting capturing the essence of dreams",
    "A captivating fusion of imagination and reality",
    "A mesmerizing visual journey through the artist's mind",
    "A magical artwork evoking a sense of wonder",
    "A visionary creation transcending conventional boundaries",
    "A surrealistic interpretation of everyday objects",
    "An enigmatic artwork inviting contemplation",
    "A dreamlike scene filled with symbolic elements",
    "A vibrant and dynamic composition that sparks curiosity",
    "A surreal representation of the subconscious mind",
    "An otherworldly landscape evoking a sense of awe",
    "A whimsical portrayal of animals in unexpected settings",
    "A surrealistic exploration of time and space",
    "A visually stunning artwork that defies logic",
    "A dreamy depiction of a parallel universe",
    "A captivating fusion of realism and abstraction",
    "An evocative artwork that challenges perception",
    "A mesmerizing blend of fantasy and reality",
    "A thought-provoking portrayal of human emotions",
    "A playful and imaginative interpretation of reality",
    "An enchanting artwork that sparks the imagination",
    "A surrealistic reflection on the nature of existence",
    "A whimsical and surreal portrayal of everyday life",
    "An extraordinary journey into the artist's imagination",
    "A dreamlike representation of the subconscious mind",
    "A whimsical and imaginative artwork that delights the senses",
    "A surrealistic exploration of the boundaries of art",
    "An enigmatic and mysterious composition that intrigues",
    "A visually striking artwork that transports the viewer",
    "A surreal depiction of the passage of time",
    "An ethereal and dreamy artwork that captivates",
    "A thought-provoking reflection on the human condition",
    "A whimsical and fantastical portrayal of reality",
    "A surrealistic vision that challenges conventional norms",
    "An intriguing and enigmatic artwork that invites interpretation",
    "A captivating blend of realism and fantasy",
    "A dreamlike representation of the natural world",
    "A surrealistic exploration of the subconscious mind",
    "An imaginative and whimsical artwork that inspires",
    "A visually stunning creation that defies expectations",
    "A surrealistic fusion of objects and forms",
    "An abstract and ethereal portrayal of emotions",
    "A mesmerizing and captivating visual experience",
    "A thought-provoking reflection on the nature of art",
    "A whimsical and fantastical interpretation of reality",
    "An evocative and enchanting artwork that sparks curiosity",
    "A surrealistic journey into the depths of the artist's mind"
  ];

  export default Random;